# sklearn_elasticnet_wine/conda.yaml
name: Application_BigData_Project
channels:
  - conda-forge
dependencies:
- python=3.9.7
- pip:
  - mlflow
  - xgboost==1.3.3
  - cloudpickle==2.0.0
  - scikit-learn==1.0.1
  - matplotlib==3.4.3
  - sphinx==4.0.1
  - seaborn==0.11.1
  - pandas==1.3.4
